zerodce:
  name: "Zero-DCE"
  type: "enhancement"
  network:
    in_channels: 3
    num_filters: 32
    kernel_size: 3
    stride: 1
    padding: 1
  loss_weights:
    illumination_smoothness: 200
    spatial_constancy: 1
    color_constancy: 5
    exposure: 10
    exposure_mean_val: 0.6